#!/home/wterry/testenv/my_env/bin/python3
##/usr/bin/env python3
import findspark
findspark.init('/opt/spark')
from pyspark.sql import SparkSession
sparkSession = SparkSession.builder.appName("example-pyspark-hdfs").getOrCreate()
sparkSession.sparkContext.setLogLevel("ERROR")
print("created Spark Session")
df_load = sparkSession.read.csv("hdfs://localhost:9000/user/will/people.csv")
df_load.show()
