#!/home/wterry/testenv/my_env/bin/python3
##/usr/bin/env python3
import pandas as pd
import findspark
import os
findspark.init('/opt/spark')
from pyspark.sql import SparkSession
print(os.getcwd())
sparkSession = SparkSession.builder.appName("example-pyspark-hdfs").getOrCreate()
print("created Spark Session")
